Repository LJOSC/checkmark-backend, pull requests merged in 2024-06, with the labels that each got.

#8 Add signup and login routes
  .eslintrc.cjs
  env.example
  models/User.ts
  package-lock.json
  package.json
  src/configs/envVars.ts
  src/index.ts
  src/routes/index.ts
  src/routes/user/user.controller.ts
  src/routes/user/user.dao.ts
  src/routes/user/user.routes.ts
  src/routes/user/user.service.ts
  src/routes/user/user.types.ts
  src/routes/user/user.validation.ts
  src/utils/HttpException.ts
  src/utils/errors.ts
  src/utils/format.ts
  src/utils/generateToken.ts
  src/utils/handleMongoError.ts
  src/utils/responseMessages.ts
  tsconfig.json
Labels: feature, API

#15 Add last login timestamp
  models/User.ts
  src/routes/user/user.service.ts
Labels: good first issue, API, mongoose

#13 Add route to verify email address after signup
  env.example
  src/configs/envVars.ts
  src/routes/user/user.controller.ts
  src/routes/user/user.routes.ts
  src/routes/user/user.service.ts
  src/services/mailing.ts
Labels: feature, API

#21 Add middlewares for access token and refresh token
  models/User.ts
  src/middlewares/verifyAccessToken.ts
  src/middlewares/verifyRefreshToken.ts
  src/routes/user/user.controller.ts
  src/routes/user/user.dao.ts
  src/types/express.d.ts
Labels: good first issue, feature, API, middleware

#23 Fix npm start script
  .eslintignore
  .gitignore
  package.json
  src/services/mailing.ts
Labels: bug

#24 Refresh Access Token API Added
  src/routes/user/user.controller.ts
  src/routes/user/user.routes.ts
  src/routes/user/user.service.ts
Labels: good first issue, API
